# Generated by Django 6.1.1 on 2026-10-04 16:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DialogSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Новая диагностика', max_length=200)),
                ('vehicle_info', models.CharField(blank=True, default='', help_text='Марка, модель, год выпуска, пробег, тип КПП/ДВС', max_length=200)),
                ('summary', models.TextField(blank=True, default='', help_text='Краткая выжимка по текущему диалогу для экономии окна контекста')),
                ('worker_status', models.CharField(choices=[('idle', 'Ожидание'), ('running', 'Фоновое обновление выжимки...'), ('aborted_for_priority', 'Воркер сброшен (приоритет новому вопросу)'), ('completed', 'Контекст синхронизирован'), ('error', 'Ошибка воркера')], default='idle', max_length=32)),
                ('worker_version', models.IntegerField(default=0, help_text='Поколение задачи воркера для мгновенного принудительного сброса')),
                ('worker_last_duration_ms', models.IntegerField(default=0)),
                ('attached_dtc_codes', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Диагностическая сессия',
                'verbose_name_plural': 'Диагностические сессии',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llm_backend', models.CharField(choices=[('airllm_vulkan', 'AirLLM Layer-wise + Vulkan (Мощные модели 14B–70B на 8 ГБ VRAM)'), ('llamacpp_vulkan', 'Llama.cpp Vulkan GGUF (Локальная модель Gemma-4 12B Q4_K_M)'), ('hybrid_auto', 'Авто-Гибрид (AirLLM + Vulkan GGUF + Экспертный синтезатор)')], default='hybrid_auto', max_length=32, verbose_name='Бэкенд ИИ и ускорения')),
                ('airllm_model_id', models.CharField(default='Qwen/Qwen2.5-32B-Instruct', max_length=160, verbose_name='Модель для послойной выгрузки AirLLM')),
                ('airllm_compression', models.CharField(choices=[('4bit', '4-bit блок-квантование (Рекомендуется для 8 ГБ VRAM)'), ('8bit', '8-bit квантование'), ('none', 'Без компрессии (FP16/BF16 послойная подгрузка с SSD)')], default='4bit', max_length=16, verbose_name='Сжатие слоев AirLLM')),
                ('gguf_model_rel_path', models.CharField(default='models/gemma-4-12b-it-Q4_K_M.gguf', max_length=255, verbose_name='Относительный путь к GGUF модели (Vulkan)')),
                ('llama_server_url', models.CharField(default='http://127.0.0.1:8080/v1', max_length=255, verbose_name='URL локального Vulkan сервера llama.cpp')),
                ('vulkan_gpu_layers', models.IntegerField(default=37, verbose_name='Слои GPU в Vulkan (под 8 ГБ VRAM)')),
                ('context_window_tokens', models.IntegerField(default=2048, verbose_name='Размер окна контекста (токенов)')),
                ('cross_dialog_memory_enabled', models.BooleanField(default=True, verbose_name='Обновлять и использовать краткую выжимку МЕЖДУ диалогами')),
                ('global_memory_summary', models.TextField(blank=True, default='', verbose_name='Глобальная междиалоговая выжимка (профиль авто и история ремонтов)')),
                ('voice_mode', models.CharField(choices=[('auto', 'Авто (Прямое аудио при поддержке модели / иначе GGML Whisper)'), ('direct_audio', 'Прямая передача аудиопотока в мультимодальную модель'), ('ggml_whisper', 'Локальное распознавание речи GGML (Whisper.cpp / Faster-Whisper)')], default='auto', max_length=32, verbose_name='Режим голосового ввода')),
                ('strict_json_mode', models.BooleanField(default=True, verbose_name='Строгий JSON формат ответа и Function Calling')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки экспертной системы',
                'verbose_name_plural': 'Настройки экспертной системы',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Пользователь'), ('assistant', 'Эксперт ИИ'), ('system', 'Система'), ('tool', 'Вызов инструмента (Function Call)')], max_length=16)),
                ('content', models.TextField()),
                ('structured_data', models.JSONField(blank=True, help_text='Валидированный JSON ответ модели: диагноз, инвентарь, чеклист задач, вызовы функций', null=True)),
                ('attachments', models.JSONField(blank=True, default=list, help_text='Прикрепленные фотографии, снимки с камеры, документы и аудиозаписи')),
                ('dtc_codes', models.JSONField(blank=True, default=list, help_text='Коды ошибок, прикрепленные к данному сообщению')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='diagnostics.dialogsession')),
            ],
            options={
                'verbose_name': 'Сообщение диагностики',
                'verbose_name_plural': 'Сообщения диагностики',
                'ordering': ['created_at'],
            },
        ),
    ]
