# Generated by Django 6.1.1 on 2026-10-05 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название проекта')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание проекта')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Проект диагностики',
                'verbose_name_plural': 'Проекты диагностики',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='dialogsession',
            options={'ordering': ['-is_pinned', '-updated_at'], 'verbose_name': 'Диагностическая сессия', 'verbose_name_plural': 'Диагностические сессии'},
        ),
        migrations.AddField(
            model_name='dialogsession',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='Закреплен вверху списка'),
        ),
        migrations.AddField(
            model_name='dialogsession',
            name='tag',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Тег категории (ДВС, АКПП, Электрика, Тормоза и т.д.)'),
        ),
        migrations.AlterField(
            model_name='dialogsession',
            name='summary',
            field=models.TextField(blank=True, default='', help_text='Краткая выжимка по текущему диалогу для динамической оптимизации окна контекста'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='airllm_compression',
            field=models.CharField(choices=[('4bit', '4-bit W4A16 QAT квантование (Оптимально для GPU от 4 до 8+ ГБ VRAM)'), ('8bit', '8-bit квантование'), ('none', 'BF16/FP16 послойная выгрузка через AirLLM')], default='4bit', max_length=16, verbose_name='Сжатие слоев AirLLM'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='airllm_model_id',
            field=models.CharField(default='models/gemma-4-12B-it', max_length=160, verbose_name='Модель AirLLM (локальный путь или HuggingFace ID)'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='context_window_tokens',
            field=models.IntegerField(default=32768, verbose_name='Размер окна контекста (токенов, в разы больше длины ответа ~5000 ток.)'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='gguf_model_rel_path',
            field=models.CharField(default='models/airllm_shards', max_length=255, verbose_name='Директория послойных шардов AirLLM'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='llama_server_url',
            field=models.CharField(default='airllm://local-gpu', max_length=255, verbose_name='Внутренний конвейер AirLLM'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='llm_backend',
            field=models.CharField(choices=[('airllm_vulkan', 'AirLLM Adaptive GPU + Layer Offload (Google Gemma 4 12B Unified Multimodal)')], default='airllm_vulkan', max_length=32, verbose_name='Бэкенд ИИ и ускорения'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='voice_mode',
            field=models.CharField(choices=[('direct_audio', 'Прямая передача аудиопотока в мультимодальную модель Gemma 4 12B (embed_audio)')], default='direct_audio', max_length=32, verbose_name='Режим голосового ввода (нативное аудио Gemma 4 12B)'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='vulkan_gpu_layers',
            field=models.IntegerField(default=36, verbose_name='Макс. резидентных слоев GPU (авто-баланс VRAM, 0..48)'),
        ),
        migrations.AddField(
            model_name='dialogsession',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='diagnostics.diagnosticproject', verbose_name='Проект'),
        ),
    ]
