# Generated by Django 6.1.1 on 2026-10-05 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0002_diagnosticproject_alter_dialogsession_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticproject',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_projects', to=settings.AUTH_USER_MODEL, verbose_name='Владелец проекта'),
        ),
        migrations.AddField(
            model_name='dialogsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dialog_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Владелец сессии'),
        ),
    ]
